dir.create("data")
dir.create("script")
dir.create("result")
patient_data <- read.csv("data/patient_info.csv")
View(patient_data)
str(patient_data)
patient_data$gender <- as.factor(patient_data$gender)
patient_data$diagnosis <- as.factor(patient_data$diagnosis)
patient_data$smoker <- as.factor(patient_data$smoker)
str(patient_data)
patient_data$smoker_binary <- ifelse(patient_data$smoker== "Yes",1,0)
patient_data$diagnosis <- factor(patient_data$diagnosis, levels = c("Normal","Cancer"))
str(patient_data)
write.csv(patient_data,file = "result/patient_info_cleaned.csv",row.names = FALSE)
